Python 3.12 requires dependency setuptools
```
% python3.12 -m pip install pipx
% pipx install setuptools-py2cfg
% setuptools-py2cfg
```
> Traceback (most recent call last):
  File "/Users/cclauss/.local/bin/setuptools-py2cfg", line 5, in <module>
    from setuptools_py2cfg import main
  File "/Users/cclauss/.local/pipx/venvs/setuptools-py2cfg/lib/python3.12/site-packages/setuptools_py2cfg.py", line 7, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'